<div class="container">
<h2> Politica de confidetialitate </h2>
<h3>I. Informatii generale</h3>
<p>Confidentialitatea datelor dumneavoastra cu caracter personal reprezinta una dintre preocuparile principale ale Bezal.el, cu sediul in [sediul detinatorul website-ului], in calitate de operator de date.
Acest document are rolul de a va informa cu privire la prelucrarea datelor dumneavoastra cu caracter personal, in contextul utilizarii paginii de internet Bezal.el. (Site-ul) <p>
<h3>II. Categoriile de date cu caracter personal prelucrate</h3>
<p>II.1. Daca sunteti client al Site-ului, Bezal.el va prelucra datele dumneavoastra cu caracter personal, cum ar fi nume şi prenume, telefon, adresa de e-mail, adresa de facturare, adresa de livrare, date referitoare la modul in care utilizati Site-ul, de exemplu comportamentul/preferinţele/obişnuintele dumneavoastra in cadrul Bezal.el, precum si orice alte categorii de date pe care le furnizati in mod direct in contextul crearii contului de utilizator, in contextul plasarii unei comenzi prin intermediul site-ului sau in orice alt mod care rezulta din utilizarea Site-ului.</p>
<p>Daca pentru a va crea cont de utilizator pe Site, utilizati contul dumneavoastra de Facebook sau Google, Bezal.el va prelucra urmatoarele date publice de profil afisate de aplicaţiile respective: nume utilizator, adresa de e-mail.</p>
<p>in cazul in care alegeti sa va creati cont de utilizator doar inainte de a finaliza comanda unui produs disponibil pe Site, se va solicita adresa dumneavoastra de e-mail in baza careia va fi creat automat un cont. in cazul in care nu finalizati comanda, adresa de e-mail si celelalte date furnizate nu vor fi stocate de Bezal.el, iar contul creat va fi sters automat.<p>
<p>II.2. Daca sunteti vizitator al Site-ului, Bezal.el va prelucra datele dumneavoastra cu caracter personal pe care le furnizati in mod direct in contextul utilizarii Site-ului, cum ar fi datele pe care le furnizati in cadrul sectiunii de contact / intrebari / reclamatii, in masura in care ne contactati in acest fel.<p>
<h3>III. Scopurile si temeiurile de prelucrarii</h3>
<p>III.1. Daca sunteti client al Site-ului, Bezal.el prelucreaza datele dumneavoastra cu caracter personal astfel:<p>
<p>- pentru desfasurarea relatiei contractuale dintre dumneavoastra şi Bezal.el, respectiv pentru preluarea, validarea, expedierea şi facturarea comenzii plasate pe Site, informarea dumneavoastra asupra starii comenzii, organizarea returului de produse comandate etc.</p>
<p><i>Temei: Prelucrarea datelor dumneavoastra in acest scop are la baza contractul incheiat intre dumneavoastra si Bezal.el, definit in cuprinsul Termenelor si Conditiilor [hyperlink la T&Cs]. Furnizarea datelor dumneavoastra cu caracter personal este necesara pentru executareaa acestui contract. Refuzul furnizarii datelor poate avea drept consecinta imposibilitatea derularii raporturilor contractuale dintre dumneavoastra si Bezal.el.</p></i>
<p>- pentru indeplinirea obligatiilor legale care incumba Bezal.el in contextul serviciilor prestate prin intermediul Site-ului, inclusiv a obligatiilor in materie fiscala, precum si in materie de arhivare.</p>
<p><i>Temei: Prelucrarea datelor dumneavoastra pentru acest scop este necesara in baza unor obligatii legale. Furnizarea datelor dumneavoastra in acest scop este necesara. Refuzul furnizarii datelor poate avea drept consecinta imposibilitatea Bezal.el de a respecta obligatiile legale care ii revin si deci in imposibilitatea de a va oferi serviciile prin intermediul Site-ului.</p></i>
<p>- pentru activitaţi de marketing, respectiv pentru transmiterea, prin intermediul mijloacelor de comunicare la distanţa (e-mail, sms) de comunicari comerciale privind produsele şi serviciile oferite de Bezal.el, prin intermediul Site-ului.</p>
<p><i>Temei: Prelucrarea datelor dumneavoastra pentru acest scop are la baza consimtamantul dumneavoastra, daca alegeti sa-l furnizati. [Nota: Trebuie colectat acord (bifa) distincta de marketing direct, care sa nu fie prebifata sau sa conditioneze finalizarea plasarii comenzii. Dovada acordului trebuie pastrata.]</p></i>
<p>Furnizarea datelor dumneavoastra in acest scop este voluntara. Refuzul furnizarii consimtamantului pentru prelucrarea datelor dumneavoastra in acest scop nu va avea urmari negative pentru dumneavoastra.</p>
<p>- in scopul efectuarii diverselor analize, raportari privind modul de functionare a Site-ului, realizarea de profiluri de preferinţe de consum, in principal, in vederea imbunataţiri experientei oferite pe Site.</p>
<p><i>Temei: Prelucrarea datelor dumneavoastra pentru acest scop are la baza interesul legitim al Bezal.el de a imbunatatii permanent experienta clientilor pe Site. Furnizarea datelor dumneavoastra in acest scop este voluntara. Refuzul furnizarii datelor pentru acest scop nu va avea urmari negative pentru dumneavoastra.</p></i>
<p>III.2. Daca sunteti vizitator al Site-ului, Bezal.el prelucreaza datele dumneavoastra cu caracter personal astfel:</p>
<p>- pentru activitaţi de marketing, respectiv pentru transmiterea, prin intermediul mijloacelor de comunicare la distanţa (e-mail, sms), de comunicari comerciale privind produsele şi serviciile oferite de Bezal.el, prin intermediul Site-ului.</p>
<p><i>Temei: Prelucrarea datelor dumneavoastra pentru acest scop are la baza consimtamantul dumneavoastra, daca alegeti sa-l furnizati.</p></i>
<p>Furnizarea datelor dumneavoastra in acest scop este voluntara. Refuzul furnizarii consimtamantului pentru prelucrarea datelor dumneavoastra in acest scop nu va avea urmari negative pentru dumneavoastra.</p>
<p>- pentru rezolvarea plangerilor, reclamaţiilor şi pentru a monitoriza traficul si a imbunataţii experienta dumneavoastra oferita pe Site.</p>
<p><i>Temei: Prelucrarea datelor dumneavoastra pentru acest scop are la baza interesul legitim al Bezal.el de a asigura functionarea corecta a Site-ului, precum si pentru a imbunatatii permanent experienta vizitatorilor Site-ului, inclusiv prin solutionarea diferitelor comentarii, intrebari sau reclamatii.</p></i>
<p>Furnizarea datelor dumneavoastra in acest scop este voluntara. Refuzul furnizarii datelor pentru acest scop nu va avea urmari negative pentru dumneavoastra.</p>
<h3>IV. Durata pentru care va prelucram datele</h3>
<p>Ca principiu, Bezal.el va prelucra datele dumneavoastra cu caracter personal atat cat este necesar pentru realizarea scopurilor de prelucrare mentionate mai sus.</p>
<p>[Nota: depastrat numai daca e cazul] in cazul in care sunteti client, vom prelucra datele dumneavoastra pe intreaga durata a raporturilor contractuale si ulterior conform obligaţiilor legale care revin in sarcina Bezal.el (de ex., in cazul documentelor justificative financiar-contabile pentru care termenul de pastrare prevazut de lege este de 10 ani de la data incheierii exerciţiului financiar in cursul caruia au fost intocmite).</p>
<p>[Nota: depastrat numai daca e cazul] in situaţia in care sunteti client si va exercitati optiunea de ştergere a contului de utilizator, prin apasarea butonul stergere cont din sectiunea Informatiile contului meu, Bezal.el va interpreta aceasta actiune ca optiunea dumneavoastra de a va dezabona de la primirea de comunicari comerciale prin care va tinem la curent despre produsele si serviciile oferite prin intermediul site-ului. in acest sens, daca alegeti sa va stergeti contul de utilizator, nu va vom mai trimite e-mailuri si/sau sms-uri de acest gen. Totusi, dorim sa va informam ca stergerea contului nu va avea ca efect automat stergerea datelor dumneavoastra cu caracter personal. in cazul in care doriti sa nu va mai fie prelucrate datele cu caracter personal sau daca doriti stergerea datelor, va puteti exercita drepturile detaliate la punctul VII de mai jos.. in cazul in care solicitati ştergerea contului, insa pe acel cont exista cel puţin o comanda activa, cererea de ştergere a contului va putea fi inregistrata numai dupa livrarea produselor şi finalizarea ultimei comenzi active.</p>
<p>Daca va retrageti consimtamantul pentru prelucrarea datelor in scop de marketing, Bezal.el va inceta prelucrarea datelor dumneavoastra cu caracter personal in acest scop, fara insa a afecta prelucrarile desfasurate de Bezal.el pe baza consimtamantului exprimat de catre dumneavoastra inainte de retragerea acestuia.</p>
<h3>V. Dezvaluirea datelor cu caracter personal</h3>
<p>Pentru indeplinirea scopurilor de prelucrare, Bezal.el poate dezvalui datele dumneavoastra catre parteneri, catre terte persoane sau entitati care sprijina Bezal.el in desfasurarea activitatii prin intermediul Site-ului (de exemplu firme de curierat, furnizori de servicii IT), ori catre autoritatile publice centrale/locale, in urmatoarele cazuri exemplificativ enumerate:<p>
<p>- pentru administrarea Site-ului;</p>
<p>- in situatiile in care aceasta comunicare ar fi necesara pentru atribuirea de premii sau alte facilitati persoanelor vizate, obtinute ca urmare a participarii lor la diverse campanii promotionale organizate de catre Bezal.el prin intermediul Site-ului;
<p>- pentru mentinerea, personalizarea si imbunatatirea Site-ului si a serviciilor derulate prin intermediul lui;
<p>- pentru efectuarea analizei datelor, testarea si cercetarea, monitorizarea tendintelor de utilizare si activitate, dezvoltarea caracteristicilor de siguranta si autentificarea utilizatorilor;
<p>- pentru transmiterea de comunicari comerciale de marketing, in conditiile si limitele prevazute de lege;
<p>- atunci cand dezvaluirea datelor cu caracter personal este prevazuta de lege etc.
<h3>VI. Transferul datelor cu caracter personal</h3>
<p>Datele cu caracter personal furnizate catre Bezal.el pot fi transferate in afara Romaniei, dar doar catre state din Uniunea Europeana. [Nota: Daca sunt transferate in afara UE, trebuie mentionate statele si care sunt garantiile pentru protectia datelor in contextul transferului.]
<h3>VII. Drepturile de care beneficiati</h3>
<p>in conditiile prevazute de legislatia in materia prelucrarii datelor cu caracter personal, in calitate de persoane vizate, beneficiati de urmatoarele drepturi:</p>
<p>- dreptul la informare, respectiv dreptul de a primi detalii privind activitatile de prelucrare efectuate de catre Bezal.el, conform celor descrise in prezentul document;</p>
<p>- dreptul de acces la date, respectiv dreptul de a obtine confirmarea din partea Bezal.el cu privire la prelucrarea datelor cu caracter personal, precum si detalii privind activitatile de prelucrare precum modalitatea in care sunt prelucrate datele, scopul in care se face prelucrarea, destinatarii sau categoriile de destinatari ai datelor, etc;</p>
<p>- dreptul la rectificare, respectiv dreptul de a obtine corectarea, fara intarzieri justificate, de catre Bezal.el a datelor cu caracter personal inexacte/ nejustificate, precum si completarea datelor incomplete; Rectificarea/ completarea va fi comunicata fiecarui destinatar la care au fost transmise datele, cu exceptia cazului in care acest lucru se dovedeste imposibil sau presupune eforturi disproportionate.</p>
<p>- dreptul la stergerea datelor, fara intarzieri nejustificate, („dreptul de a fi uitat”), in cazul in care se aplica unul dintre urmatoarele motive:</p>
<p>- acestea nu mai sunt necesare pentru indeplinirea scopurilor pentru care au fost colectate sau prelucrate;</p>
<p>- in cazul in care este retras consimtamantul si nu exista niciun alt temei juridic pentru prelucrare;</p>
<p>- in cazul in care persoana vizata se opune prelucrarii si nu exista motive legitime care sa prevaleze;</p>
<p>- in cazul in care datele cu caracter personal au fost prelucrate ilegal;</p>
<p>- in cazul in care datele cu caracter personal trebuie sterse pentru respectarea unei obligatii legale;</p>
<p>- datele cu caracter personal au fost colectate in legatura cu oferirea de servicii ale societatii informationale conform dreptului Uniunii sau al dreptului intern sub incidenta caruia se afla operatorul.</p>
<p>Este posibil ca, in urma solicitarii de stergere a datelor, Bezal.el sa anonimizeze aceste date (lipsindu-le astfel de caracterul personal) si sa continue in aceste conditii prelucrarea pentru scopuri statistice;</p>
<p>Pentru orice intrebari suplimentare cu privire la modul in care datele cu caracter personal sunt prelucrate si pentru a va exercita drepturile mentionate mai sus, va rugam sa va adresati la adresa de email: [de adaugat].</p>

</div>
